---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - telemetry.amasuda.xyz
  resources:
  - switchbots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.amasuda.xyz
  resources:
  - switchbots/finalizers
  verbs:
  - update
- apiGroups:
  - telemetry.amasuda.xyz
  resources:
  - switchbots/status
  verbs:
  - get
  - patch
  - update
